In [181]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 

In [215]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [225]:
n_data = pd.read_csv("E:\Transaction Detect\Trasaction.csv")

In [227]:
n_data.head()

Unnamed: 0  TransactionID      TransactionDate  TransactionAmount  \
0           0              1  2023-01-01 00:00:00             375.17   
1           1              2  2023-01-01 01:00:00             950.76   
2           2              3  2023-01-01 02:00:00             732.26   
3           3              4  2023-01-01 03:00:00             599.06   
4           4              5  2023-01-01 04:00:00             156.86   

   MerchantID TransactionType  CardPresent  IsFraud  
0        1020        Purchase        False        0  
1        1063      Withdrawal         True        0  
2        1036          Refund        False        0  
3        1026        Purchase         True        0  
4        1054         Deposit         True        0

In [304]:
n_data["IsFraud"].sum()

193

In [229]:
n_data["TransactionType"].unique()

array(['Purchase', 'Withdrawal', 'Refund', 'Deposit'], dtype=object)

In [183]:
data = pd.read_csv("E:\Transaction Detect\Trasaction.csv")

In [185]:
data.shape

(4000, 8)

In [187]:
#data.isnull().sum()

In [189]:
data.head()

Unnamed: 0  TransactionID      TransactionDate  TransactionAmount  \
0           0              1  2023-01-01 00:00:00             375.17   
1           1              2  2023-01-01 01:00:00             950.76   
2           2              3  2023-01-01 02:00:00             732.26   
3           3              4  2023-01-01 03:00:00             599.06   
4           4              5  2023-01-01 04:00:00             156.86   

   MerchantID TransactionType  CardPresent  IsFraud  
0        1020        Purchase        False        0  
1        1063      Withdrawal         True        0  
2        1036          Refund        False        0  
3        1026        Purchase         True        0  
4        1054         Deposit         True        0

In [191]:
data.drop(["Unnamed: 0"],axis = 1 ,inplace = True)

In [193]:
data.head()

TransactionID      TransactionDate  TransactionAmount  MerchantID  \
0              1  2023-01-01 00:00:00             375.17        1020   
1              2  2023-01-01 01:00:00             950.76        1063   
2              3  2023-01-01 02:00:00             732.26        1036   
3              4  2023-01-01 03:00:00             599.06        1026   
4              5  2023-01-01 04:00:00             156.86        1054   

  TransactionType  CardPresent  IsFraud  
0        Purchase        False        0  
1      Withdrawal         True        0  
2          Refund        False        0  
3        Purchase         True        0  
4         Deposit         True        0

In [195]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   TransactionID      4000 non-null   int64  
 1   TransactionDate    4000 non-null   object 
 2   TransactionAmount  4000 non-null   float64
 3   MerchantID         4000 non-null   int64  
 4   TransactionType    4000 non-null   object 
 5   CardPresent        4000 non-null   bool   
 6   IsFraud            4000 non-null   int64  
dtypes: bool(1), float64(1), int64(3), object(2)
memory usage: 191.5+ KB


In [197]:
data.columns

Index(['TransactionID', 'TransactionDate', 'TransactionAmount', 'MerchantID',
       'TransactionType', 'CardPresent', 'IsFraud'],
      dtype='object')

In [199]:
data['TransactionDate'] = pd.to_datetime(data['TransactionDate'])

In [201]:
data['TransactionHour'] = data['TransactionDate'].dt.hour
data['TransactionDay'] = data['TransactionDate'].dt.day_name()
data['TransactionWeek'] = data['TransactionDate'].dt.isocalendar().week
data['TransactionMonth'] = df['TransactionDate'].dt.month_name()

In [203]:
data.head()

TransactionID     TransactionDate  TransactionAmount  MerchantID  \
0              1 2023-01-01 00:00:00             375.17        1020   
1              2 2023-01-01 01:00:00             950.76        1063   
2              3 2023-01-01 02:00:00             732.26        1036   
3              4 2023-01-01 03:00:00             599.06        1026   
4              5 2023-01-01 04:00:00             156.86        1054   

  TransactionType  CardPresent  IsFraud  TransactionHour TransactionDay  \
0        Purchase        False        0                0         Sunday   
1      Withdrawal         True        0                1         Sunday   
2          Refund        False        0                2         Sunday   
3        Purchase         True        0                3         Sunday   
4         Deposit         True        0                4         Sunday   

   TransactionWeek TransactionMonth  
0               52          January  
1               52          January  
2               52          January  
3               52          January  
4               52          January

In [205]:
data['TransactionDate'] = data['TransactionDate'].view('int64')

C:\Users\Admin\AppData\Local\Temp\ipykernel_9852\1566571560.py:1: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  data['TransactionDate'] = data['TransactionDate'].view('int64')


In [177]:
import pandas as pd

# Assuming 'data' is your existing dataframe
data = pd.get_dummies(data, columns=["TransactionType", "CardPresent", "TransactionDay", "TransactionMonth"]).astype(int)

In [209]:
data.drop(["TransactionDate"],axis = 1 , inplace = True)

In [211]:
data.head()

TransactionID  TransactionAmount  MerchantID TransactionType  CardPresent  \
0              1             375.17        1020        Purchase        False   
1              2             950.76        1063      Withdrawal         True   
2              3             732.26        1036          Refund        False   
3              4             599.06        1026        Purchase         True   
4              5             156.86        1054         Deposit         True   

   IsFraud  TransactionHour TransactionDay  TransactionWeek TransactionMonth  
0        0                0         Sunday               52          January  
1        0                1         Sunday               52          January  
2        0                2         Sunday               52          January  
3        0                3         Sunday               52          January  
4        0                4         Sunday               52          January

In [213]:
data.columns

Index(['TransactionID', 'TransactionAmount', 'MerchantID', 'TransactionType',
       'CardPresent', 'IsFraud', 'TransactionHour', 'TransactionDay',
       'TransactionWeek', 'TransactionMonth'],
      dtype='object')

In [217]:
le_transaction_type = LabelEncoder()
le_card_present = LabelEncoder()
le_transaction_day = LabelEncoder()
le_transaction_month = LabelEncoder()

In [219]:
data['TransactionType'] = le_transaction_type.fit_transform(data['TransactionType'])
data['CardPresent'] = le_card_present.fit_transform(data['CardPresent'])
data['TransactionDay'] = le_transaction_day.fit_transform(data['TransactionDay'])
data['TransactionMonth'] = le_transaction_month.fit_transform(data['TransactionMonth'])

In [221]:
data

TransactionID  TransactionAmount  MerchantID  TransactionType  \
0                 1             375.17        1020                1   
1                 2             950.76        1063                3   
2                 3             732.26        1036                2   
3                 4             599.06        1026                1   
4                 5             156.86        1054                0   
...             ...                ...         ...              ...   
3995           3996             442.66        1066                2   
3996           3997             335.07        1081                2   
3997           3998             395.18        1077                0   
3998           3999             530.41        1030                0   
3999           4000             162.21        1090                3   

      CardPresent  IsFraud  TransactionHour  TransactionDay  TransactionWeek  \
0               0        0                0               3               52   
1               1        0                1               3               52   
2               0        0                2               3               52   
3               1        0                3               3               52   
4               1        0                4               3               52   
...           ...      ...              ...             ...              ...   
3995            1        1               11               0               24   
3996            0        0               12               0               24   
3997            0        1               13               0               24   
3998            1        0               14               0               24   
3999            1        0               15               0               24   

      TransactionMonth  
0                    2  
1                    2  
2                    2  
3                    2  
4                    2  
...                ...  
3995                 3  
3996                 3  
3997                 3  
3998                 3  
3999                 3  

[4000 rows x 10 columns]

In [223]:
data["TransactionType"].unique()

array([1, 3, 2, 0])

In [231]:
data["CardPresent"].unique()

array([0, 1], dtype=int64)

In [233]:
X = data.drop(["IsFraud"],axis = 1)
y= data["IsFraud"]

In [235]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [237]:
model = RandomForestClassifier(random_state=42)

In [239]:
model

RandomForestClassifier(random_state=42)

In [241]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [298]:
y_pred = model.predict(X_test)

In [300]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [245]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.95125
Confusion Matrix:
 [[761   0]
 [ 39   0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.95      1.00      0.98       761
           1       0.00      0.00      0.00        39

    accuracy                           0.95       800
   macro avg       0.48      0.50      0.49       800
weighted avg       0.90      0.95      0.93       800



C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

In [253]:
y_pred = pd.DataFrame(y_pred)

In [257]:
y_pred.rename(columns = {0:"y_pred"},inplace = True)

In [259]:
y_pred.head()

y_pred
0       0
1       0
2       0
3       0
4       0

In [263]:
y_test = pd.DataFrame(y_test)

In [267]:
y_test.reset_index(inplace = True)

In [271]:
y_test.drop(["index"],axis = 1 , inplace = True)

In [273]:
y_test

IsFraud
0          0
1          0
2          0
3          0
4          0
..       ...
795        0
796        0
797        0
798        0
799        0

[800 rows x 1 columns]

In [278]:
X_test.reset_index(inplace = True)

In [282]:
X_test.drop(["index"],axis= 1 , inplace = True)

In [284]:
X_test

TransactionID  TransactionAmount  MerchantID  TransactionType  \
0              556             404.08        1005                2   
1             3492             607.24        1071                0   
2              528             274.13        1032                3   
3             3926              26.74        1038                1   
4             2990             862.78        1071                1   
..             ...                ...         ...              ...   
795           1923             619.97        1040                1   
796            866             560.08        1008                0   
797           3944             393.71        1067                3   
798           1643             521.44        1041                1   
799           2484             149.65        1026                0   

     CardPresent  TransactionHour  TransactionDay  TransactionWeek  \
0              1                3               5                4   
1              1               11               0               21   
2              1               23               3                3   
3              0               13               5               24   
4              0               13               0               18   
..           ...              ...             ...              ...   
795            0                2               6               12   
796            1                1               1                6   
797            1                7               6               24   
798            1               10               0               10   
799            1               11               0               15   

     TransactionMonth  
0                   2  
1                   5  
2                   2  
3                   3  
4                   5  
..                ...  
795                 4  
796                 1  
797                 3  
798                 4  
799                 0  

[800 rows x 9 columns]

In [286]:
Conclusion = pd.concat([data,y_test,y_pred],axis = 1)

In [288]:
Conclusion.head()

TransactionID  TransactionAmount  MerchantID  TransactionType  CardPresent  \
0              1             375.17        1020                1            0   
1              2             950.76        1063                3            1   
2              3             732.26        1036                2            0   
3              4             599.06        1026                1            1   
4              5             156.86        1054                0            1   

   IsFraud  TransactionHour  TransactionDay  TransactionWeek  \
0        0                0               3               52   
1        0                1               3               52   
2        0                2               3               52   
3        0                3               3               52   
4        0                4               3               52   

   TransactionMonth  IsFraud  y_pred  
0                 2      0.0     0.0  
1                 2      0.0     0.0  
2                 2      0.0     0.0  
3                 2      0.0     0.0  
4                 2      0.0     0.0

In [292]:
Conclusion["IsFraud"].sum()

IsFraud    193.0
IsFraud     39.0
dtype: float64

In [294]:
Conclusion["y_pred"].sum()

0.0

In [296]:
y_pred

y_pred
0         0
1         0
2         0
3         0
4         0
..      ...
795       0
796       0
797       0
798       0
799       0

[800 rows x 1 columns]

In [302]:
Conclusion["IsFraud"].sum()

IsFraud    193.0
IsFraud     39.0
dtype: float64